project:
  type: book  
  output-dir: docs

book:
  title: "Gulf Cooling Water and Peak Demand: Thermal Risk for Coastal Generation"
  author: "Ryan Flatley"
  page-footer:
    left: "Copyright 2026, Ryan Flatley"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - references.qmd
  appendices:
    - draft-data-doc.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt

